// Full exercise library — 30 exercises across all muscle groups
// Each has: id, name, emoji, muscle, category, difficulty, 
//           how (5 steps), tip, cue, mod (beginner modification)
// startWeight/increment for weighted exercises, durationSecs for holds/cardio

export const EXERCISES = [
  // ── LEGS ────────────────────────────────────────────────────────────────
  {
    id: 'goblet_squat', name: 'Goblet Squat', emoji: '🏋️', muscle: 'Quads & glutes',
    category: 'legs', difficulty: 'beginner', weighted: true, startWeight: 10, increment: 2, unit: 'kg',
    how: ['Hold a dumbbell vertically at your chest, both hands cupped underneath.', 'Stand feet shoulder-width, toes turned out slightly.', 'Sit back and down — chest up, like lowering onto a low chair.', 'Go until thighs are parallel to floor or as low as comfortable.', 'Drive through heels to stand. Squeeze glutes at the top.'],
    tip: 'If heels lift, put a small plate under each heel until ankles loosen up.',
    cue: 'Chest up, sit back not down.', mod: 'Hold a chair back for balance.',
  },
  {
    id: 'romanian_deadlift', name: 'Romanian Deadlift', emoji: '🔄', muscle: 'Hamstrings & glutes',
    category: 'legs', difficulty: 'beginner', weighted: true, startWeight: 15, increment: 2.5, unit: 'kg each hand',
    how: ['Hold dumbbells in front of thighs, standing hip-width apart.', 'Push hips back — not down — and lower dumbbells along your legs.', 'Lower until you feel a hamstring stretch, around mid-shin level.', 'Drive hips forward to stand. Squeeze glutes at the top.', 'Keep a flat back throughout — no rounding.'],
    tip: 'Think hip hinge, not squat. Hips go back, knees barely bend.',
    cue: 'Feel the stretch in your hamstrings before coming back up.',
    mod: 'Use lighter weight and only go to knee height until flexible.',
  },
  {
    id: 'lunge', name: 'Reverse Lunge', emoji: '🎯', muscle: 'Quads, glutes & balance',
    category: 'legs', difficulty: 'beginner', weighted: false, durationSecs: null,
    how: ['Stand tall, feet hip-width apart.', 'Step one foot back and lower your back knee toward the floor.', 'Front thigh should be parallel to the floor.', 'Drive through your front heel to return to standing.', 'Alternate legs each rep.'],
    tip: 'Reverse lunge (stepping back) is easier on the knees than forward lunge.',
    cue: 'Keep your torso upright — don\'t lean forward.',
    mod: 'Hold a wall or chair for balance while learning.',
  },
  {
    id: 'jump_squat', name: 'Jump Squat', emoji: '🚀', muscle: 'Quads, glutes & power',
    category: 'legs', difficulty: 'intermediate', weighted: false,
    how: ['Stand feet shoulder-width apart.', 'Squat down until thighs are parallel to floor.', 'Explode upward into a jump, arms swinging for momentum.', 'Land softly with bent knees, absorbing the impact.', 'Go straight into the next rep.'],
    tip: 'Land quietly — if you\'re making a loud thud, bend your knees more on landing.',
    cue: 'Explode up, land soft.', mod: 'Regular squat — remove the jump entirely.',
  },
  {
    id: 'wall_sit', name: 'Wall Sit', emoji: '🧱', muscle: 'Quads endurance',
    category: 'legs', difficulty: 'beginner', weighted: false, durationSecs: 30,
    how: ['Stand with your back flat against a wall.', 'Slide down until thighs are parallel to the floor.', 'Feet should be hip-width, directly below your knees.', 'Hold this position — breathe steadily.', 'Back stays flat against the wall throughout.'],
    tip: 'If your thighs aren\'t parallel, it\'s not a wall sit. Go lower.',
    cue: 'Back flat, thighs parallel.', mod: 'Only go as low as comfortable — even 45° builds strength.',
  },
  {
    id: 'glute_bridge', name: 'Glute Bridge', emoji: '🌉', muscle: 'Glutes & hamstrings',
    category: 'legs', difficulty: 'beginner', weighted: false,
    how: ['Lie on your back, knees bent, feet flat on floor hip-width apart.', 'Drive through your heels and lift your hips toward the ceiling.', 'Squeeze your glutes hard at the top.', 'Hold for 1 second at the top.', 'Lower slowly back to the floor.'],
    tip: 'Don\'t let your lower back arch excessively — squeeze glutes, not back.',
    cue: 'Drive heels into floor, squeeze glutes at top.',
    mod: 'Perfect beginner exercise — no modification needed.',
  },
  // ── PUSH ─────────────────────────────────────────────────────────────────
  {
    id: 'dumbbell_bench', name: 'Dumbbell Bench Press', emoji: '💪', muscle: 'Chest & triceps',
    category: 'push', difficulty: 'beginner', weighted: true, startWeight: 12, increment: 2, unit: 'kg each hand',
    how: ['Lie flat on a bench, feet flat on floor.', 'Hold dumbbells at chest height, elbows at ~45° from body.', 'Press both dumbbells up until arms are almost fully extended.', 'Lower slowly — 2 seconds down.', 'Keep shoulder blades squeezed together throughout.'],
    tip: 'Don\'t flare elbows wide — 45° angle protects your shoulders.',
    cue: 'Squeeze chest at the top, control on the way down.',
    mod: 'Reduce weight significantly and focus on the movement pattern first.',
  },
  {
    id: 'press_up', name: 'Press Up', emoji: '⬇️', muscle: 'Chest, shoulders & triceps',
    category: 'push', difficulty: 'beginner', weighted: false,
    how: ['Hands slightly wider than shoulders, body in a straight line.', 'Lower your chest to the floor — elbows at about 45°.', 'Keep your core braced throughout.', 'Push back up to the start.', 'Don\'t let hips sag or pike up.'],
    tip: 'If you can\'t do a full press up, do knee press ups until you build strength.',
    cue: 'Body like a plank — no sagging hips.', mod: 'Knee press ups — keep a straight line from knees to shoulders.',
  },
  {
    id: 'shoulder_press', name: 'Dumbbell Shoulder Press', emoji: '⬆️', muscle: 'Shoulders & triceps',
    category: 'push', difficulty: 'beginner', weighted: true, startWeight: 8, increment: 2, unit: 'kg each hand',
    how: ['Sit on a bench or stand feet shoulder-width apart.', 'Hold dumbbells at shoulder height, palms facing forward.', 'Press both dumbbells up until arms are nearly extended.', 'Lower slowly back to shoulder height.', 'Keep core braced — don\'t arch your lower back.'],
    tip: 'Seated prevents you using legs to cheat the weight up.',
    cue: 'Press straight up, don\'t lean back.', mod: 'Seated version is easier — use a chair with back support.',
  },
  {
    id: 'tricep_dip', name: 'Tricep Dip', emoji: '📉', muscle: 'Triceps & chest',
    category: 'push', difficulty: 'beginner', weighted: false,
    how: ['Sit on the edge of a sturdy chair, hands gripping the edge beside your hips.', 'Slide your bum off the chair, legs extended in front.', 'Lower yourself by bending your elbows to about 90°.', 'Push back up by straightening your arms.', 'Keep your back close to the chair throughout.'],
    tip: 'The further your feet are from the chair, the harder this is.',
    cue: 'Elbows point backward, not out to the sides.',
    mod: 'Bend your knees to reduce the load.',
  },
  {
    id: 'lateral_raise', name: 'Lateral Raise', emoji: '↔️', muscle: 'Side shoulders',
    category: 'push', difficulty: 'beginner', weighted: true, startWeight: 5, increment: 1, unit: 'kg each hand',
    how: ['Stand holding light dumbbells by your sides.', 'With a slight bend in your elbows, raise both arms out to the sides.', 'Stop when arms are at shoulder height — no higher.', 'Lower slowly back down — 3 seconds.', 'Don\'t use momentum or shrug your shoulders.'],
    tip: 'This is a light-weight exercise — ego check required. Form matters more than weight.',
    cue: 'Lead with your elbows, not your hands.', mod: 'Use very light weight or just bodyweight at first.',
  },
  // ── PULL ─────────────────────────────────────────────────────────────────
  {
    id: 'lat_pulldown', name: 'Lat Pulldown', emoji: '🔽', muscle: 'Back & biceps',
    category: 'pull', difficulty: 'beginner', weighted: true, startWeight: 30, increment: 5, unit: 'kg stack',
    how: ['Grip bar wider than shoulder-width, palms facing away.', 'Tuck knees under the pad. Sit tall.', 'Pull bar to your upper chest, leading with your elbows.', 'Pause at the bottom, squeeze your lats.', 'Let bar rise slowly — 2 seconds up.'],
    tip: 'If you\'re swinging backwards to pull, the weight is too heavy.',
    cue: 'Pull elbows down and back, like you\'re putting them in your back pockets.',
    mod: 'Reduce weight significantly — you should feel it in your back, not arms.',
  },
  {
    id: 'dumbbell_row', name: 'Single-Arm Dumbbell Row', emoji: '🚣', muscle: 'Back & biceps',
    category: 'pull', difficulty: 'beginner', weighted: true, startWeight: 12, increment: 2.5, unit: 'kg',
    how: ['Place one knee and hand on a bench for support.', 'Hold a dumbbell in the other hand, arm hanging straight down.', 'Pull the dumbbell up toward your hip, leading with your elbow.', 'Squeeze your back at the top.', 'Lower slowly back to full arm extension.'],
    tip: 'Keep your back flat and parallel to the floor throughout.',
    cue: 'Elbow to hip, not elbow to shoulder.', mod: 'Use a lighter weight and focus on feeling your back work.',
  },
  {
    id: 'face_pull', name: 'Band Face Pull', emoji: '😤', muscle: 'Rear shoulders & upper back',
    category: 'pull', difficulty: 'beginner', weighted: false,
    how: ['Attach a resistance band at head height to a door or pole.', 'Hold the band with both hands, arms extended in front.', 'Pull the band toward your face, elbows flaring out to the sides.', 'Finish with hands beside your ears, thumbs pointing behind you.', 'Return slowly to the start.'],
    tip: 'Underused exercise that fixes shoulder posture and prevents injury.',
    cue: 'Elbows high and wide — hands end up beside ears.',
    mod: 'Use a light resistance band — this should be done for reps not max weight.',
  },
  {
    id: 'bicep_curl', name: 'Dumbbell Bicep Curl', emoji: '💪', muscle: 'Biceps',
    category: 'pull', difficulty: 'beginner', weighted: true, startWeight: 8, increment: 1, unit: 'kg each hand',
    how: ['Stand holding dumbbells by your sides, palms facing forward.', 'Curl both dumbbells up toward your shoulders.', 'Squeeze your biceps at the top.', 'Lower slowly — 3 seconds down.', 'Keep elbows pinned to your sides throughout.'],
    tip: 'If your elbows are swinging forward you\'re using momentum — reduce weight.',
    cue: 'Elbows stay still — only your forearms move.', mod: 'Use lighter weight and do one arm at a time.',
  },
  // ── CORE ─────────────────────────────────────────────────────────────────
  {
    id: 'plank', name: 'Plank', emoji: '🧱', muscle: 'Core',
    category: 'core', difficulty: 'beginner', weighted: false, durationSecs: 30,
    how: ['Forearms on floor, elbows under shoulders.', 'Body forms a straight line from head to heels.', 'Brace your core like you\'re about to take a punch.', 'Hold — breathe normally.', 'If form breaks, stop and rest.'],
    tip: 'Quality over duration. A 20-second perfect plank beats a 60-second saggy one.',
    cue: 'Squeeze glutes and core. Don\'t let hips drop.', mod: 'Knee plank — still keep a straight line from knees to shoulders.',
  },
  {
    id: 'dead_bug', name: 'Dead Bug', emoji: '🐛', muscle: 'Deep core',
    category: 'core', difficulty: 'beginner', weighted: false,
    how: ['Lie on your back, arms pointing at the ceiling, knees above hips at 90°.', 'Press your lower back firmly into the floor.', 'Slowly lower your right arm and left leg toward the floor.', 'Stop just before your lower back peels off the floor.', 'Return to start and repeat on the other side.'],
    tip: 'The lower back must stay pressed into the floor the entire time.',
    cue: 'Slow and controlled — never rush this exercise.',
    mod: 'Just lower your legs, keep arms pointing up, until you build coordination.',
  },
  {
    id: 'russian_twist', name: 'Russian Twist', emoji: '🌀', muscle: 'Obliques',
    category: 'core', difficulty: 'intermediate', weighted: false,
    how: ['Sit on the floor, knees bent, feet flat or lifted slightly.', 'Lean back slightly — keep your back straight, not hunched.', 'Clasp hands together in front of you.', 'Rotate your torso to touch the floor on one side.', 'Rotate to the other side — that\'s one rep.'],
    tip: 'The rotation comes from your torso, not just your arms swinging.',
    cue: 'Rotate from your ribs, not your shoulders.',
    mod: 'Keep feet flat on floor to reduce difficulty.',
  },
  {
    id: 'leg_raise', name: 'Lying Leg Raise', emoji: '🦵', muscle: 'Lower abs',
    category: 'core', difficulty: 'intermediate', weighted: false,
    how: ['Lie flat on your back, legs straight, hands under your lower back.', 'Keeping legs straight, raise them to 90° above the floor.', 'Lower them slowly back down — 3 seconds.', 'Stop just before your heels touch the floor.', 'Keep your lower back pressed to the floor throughout.'],
    tip: 'If your lower back arches, you\'ve gone too low. Build strength first.',
    cue: 'Lower back stays glued to the floor.',
    mod: 'Bend knees slightly to reduce the load.',
  },
  {
    id: 'mountain_climber', name: 'Mountain Climbers', emoji: '🏔️', muscle: 'Core & cardio',
    category: 'core', difficulty: 'beginner', weighted: false,
    how: ['Get into a plank position, hands under shoulders.', 'Drive one knee toward your chest.', 'Quickly swap legs — like running on the spot horizontally.', 'Keep your hips level throughout.', 'Faster = more cardio, slower = more core work.'],
    tip: 'Don\'t let your hips rise up as you speed up.',
    cue: 'Hips stay level — don\'t let them bob up and down.',
    mod: 'Slow march instead of running — step one knee in, step back, swap.',
  },
  // ── CARDIO ───────────────────────────────────────────────────────────────
  {
    id: 'burpee', name: 'Burpee', emoji: '💥', muscle: 'Full body cardio',
    category: 'cardio', difficulty: 'intermediate', weighted: false,
    how: ['Stand, then squat down and place hands on floor.', 'Jump or step feet back into a plank position.', 'Do a press up (optional but adds difficulty).', 'Jump or step feet back to your hands.', 'Jump up with arms overhead — that\'s one rep.'],
    tip: 'Scale by removing the press up and/or stepping instead of jumping.',
    cue: 'Keep moving — pace doesn\'t matter, stopping does.',
    mod: 'Step feet back and in instead of jumping. Skip the jump at the top.',
  },
  {
    id: 'high_knees', name: 'High Knees', emoji: '🦿', muscle: 'Legs & cardio',
    category: 'cardio', difficulty: 'beginner', weighted: false,
    how: ['Run on the spot, driving knees up to hip height.', 'Arms pump in time with your legs.', 'Land on the balls of your feet.', 'Keep your torso upright — don\'t lean back.', 'Aim for a fast, light rhythm.'],
    tip: 'The higher the knees, the more work. Start lower and build up.',
    cue: 'Drive knees up, not just feet back.', mod: 'March on the spot — lift knees high without the bounce.',
  },
  {
    id: 'star_jump', name: 'Star Jump', emoji: '⭐', muscle: 'Full body cardio',
    category: 'cardio', difficulty: 'beginner', weighted: false,
    how: ['Start standing, feet together, arms by sides.', 'Jump feet out wide as you raise arms overhead.', 'Land softly with bent knees.', 'Jump feet back together and lower arms.', 'Keep a steady rhythm.'],
    tip: 'Land softly — if it\'s loud, bend your knees more on landing.',
    cue: 'Arms and legs move together.', mod: 'Step side to side instead of jumping.',
  },
  {
    id: 'box_step', name: 'Step Up', emoji: '📦', muscle: 'Glutes & legs',
    category: 'cardio', difficulty: 'beginner', weighted: false,
    how: ['Stand in front of a sturdy chair, step, or box.', 'Step one foot onto the surface.', 'Drive through that heel to bring your whole body up.', 'Step back down with control.', 'Alternate lead legs each rep.'],
    tip: 'The higher the step, the more glute work.',
    cue: 'Push through the heel of the raised foot — don\'t push off the floor.',
    mod: 'Use a lower surface (a thick book or bottom stair) to start.',
  },
  {
    id: 'skipping', name: 'Skipping (Jump Rope)', emoji: '🪢', muscle: 'Cardio & calves',
    category: 'cardio', difficulty: 'beginner', weighted: false, durationSecs: 60,
    how: ['Hold handles at hip height, rope behind you.', 'Swing the rope over your head and jump as it comes under your feet.', 'Land on the balls of your feet, slight knee bend.', 'Keep jumps small — just enough to clear the rope.', 'Find a steady rhythm before trying to speed up.'],
    tip: 'No rope? Pretend. The arm motion and jumping still works your heart.',
    cue: 'Small jumps, wrists doing the work not arms.',
    mod: 'Jump without a rope to learn the rhythm first.',
  },
  // ── MOBILITY/FLEXIBILITY ─────────────────────────────────────────────────
  {
    id: 'hip_flexor_stretch', name: 'Hip Flexor Stretch', emoji: '🧘', muscle: 'Hip flexors',
    category: 'mobility', difficulty: 'beginner', weighted: false, durationSecs: 30,
    how: ['Kneel on one knee, the other foot in front (like a proposal position).', 'Keep your torso upright.', 'Shift your hips forward until you feel a stretch in the front of your back hip.', 'Hold — breathe deeply.', 'Swap sides.'],
    tip: 'Sitting at a desk all day tightens hip flexors badly. Do this daily.',
    cue: 'Hips forward, torso upright — don\'t lean forward.',
    mod: 'Place a folded towel under your knee for comfort.',
  },
  {
    id: 'world_greatest_stretch', name: 'World\'s Greatest Stretch', emoji: '🌍', muscle: 'Full body mobility',
    category: 'mobility', difficulty: 'beginner', weighted: false,
    how: ['Start in a press up position.', 'Step one foot outside your same-side hand.', 'Drop your back knee to the floor.', 'Rotate your top arm up toward the ceiling, following it with your eyes.', 'Return to start and repeat on the other side.'],
    tip: 'Arguably the single best warm-up exercise — hits hip flexors, thoracic spine, and ankles.',
    cue: 'Rotate from your chest, not just your arm.',
    mod: 'Skip the rotation at first — just hold the lunge position.',
  },
  {
    id: 'cat_cow', name: 'Cat-Cow', emoji: '🐱', muscle: 'Spine mobility',
    category: 'mobility', difficulty: 'beginner', weighted: false,
    how: ['Get on all fours, hands under shoulders, knees under hips.', 'Inhale: let your belly drop, lift your head and tailbone (cow).', 'Exhale: round your spine up toward the ceiling, tuck chin and tailbone (cat).', 'Move slowly and with your breath.', 'Do 8–10 slow reps.'],
    tip: 'Perfect for back pain and stiffness, especially first thing in the morning.',
    cue: 'Move with your breath — inhale to arch, exhale to round.',
    mod: 'Perfect as-is for any level.',
  },
  {
    id: 'thoracic_rotation', name: 'Thoracic Rotation', emoji: '🔄', muscle: 'Upper back mobility',
    category: 'mobility', difficulty: 'beginner', weighted: false, durationSecs: 20,
    how: ['Lie on your side, knees stacked and bent at 90°.', 'Extend arms in front of you, hands together.', 'Keeping your knees still, rotate your top arm back across your body.', 'Follow your hand with your eyes.', 'Return slowly and repeat. Do both sides.'],
    tip: 'If your knees lift off the floor, you\'re going too far.',
    cue: 'Knees stay still — only your upper body rotates.',
    mod: 'Perfect as-is — great for desk workers and runners.',
  },
  // ── FULL BODY ─────────────────────────────────────────────────────────────
  {
    id: 'kettlebell_swing', name: 'Dumbbell Swing', emoji: '🎿', muscle: 'Full body power',
    category: 'full_body', difficulty: 'intermediate', weighted: true, startWeight: 12, increment: 2, unit: 'kg',
    how: ['Hold one dumbbell with both hands, feet shoulder-width apart.', 'Hinge at the hips and swing the dumbbell back between your legs.', 'Drive your hips forward explosively to swing it up to chest height.', 'Let it swing back down and immediately hinge again.', 'Power comes from hips, not arms.'],
    tip: 'This is a hip hinge not a squat. Your back stays flat throughout.',
    cue: 'Hips drive the swing — arms just guide it.', mod: 'Use a lighter weight and do slow controlled reps to learn the pattern.',
  },
  {
    id: 'thruster', name: 'Dumbbell Thruster', emoji: '🔥', muscle: 'Legs, shoulders & core',
    category: 'full_body', difficulty: 'intermediate', weighted: true, startWeight: 8, increment: 2, unit: 'kg each hand',
    how: ['Hold dumbbells at shoulder height, feet shoulder-width.', 'Squat down until thighs are parallel to floor.', 'As you drive up from the squat, press the dumbbells overhead.', 'Lower the dumbbells back to shoulders as you descend into the next squat.', 'It\'s one fluid movement — squat into press.'],
    tip: 'Use the momentum from the squat to help drive the press — that\'s the point.',
    cue: 'Squat and press in one smooth movement.',
    mod: 'Do the squat and press separately until the coordination clicks.',
  },
];

export const CATEGORIES = [
  { id: 'legs',      label: 'Legs',        emoji: '🦵' },
  { id: 'push',      label: 'Push',        emoji: '⬆️' },
  { id: 'pull',      label: 'Pull',        emoji: '⬇️' },
  { id: 'core',      label: 'Core',        emoji: '🌀' },
  { id: 'cardio',    label: 'Cardio',      emoji: '🏃' },
  { id: 'mobility',  label: 'Mobility',    emoji: '🧘' },
  { id: 'full_body', label: 'Full Body',   emoji: '💥' },
];

export const getExerciseById = (id) => EXERCISES.find(e => e.id === id);
export const getByCategory = (cat) => EXERCISES.filter(e => e.category === cat);
